<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->

<robot name="sensor_d435" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sensor_d435" params="parent *origin">
    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  
    <!-- The following values model the aluminum peripherial case for the
  	D435 camera, with the camera joint represented by the actual 
  	peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  
    <!-- The following offset is relative the the physical D435 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

    <material name="aluminum1">
	  <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- camera body, with origin at bottom screw mount -->
    <joint name="camera_joint1" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="camera_bottom_screw_frame1" />
    </joint>
    <link name="camera_bottom_screw_frame1"/>

    <joint name="camera_link1_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="camera_bottom_screw_frame1"/>
      <child link="camera_link1" />
    </joint>

    <link name="camera_link1">
      <visual>
      <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/d435.stl" scale="0.01 0.01 0.01" />
        </geometry>
        <material name="aluminum1"/>
      </visual>
      <collision>
        <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/d435.stl" scale="0.01 0.01 0.01" />
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <!-- camera depth joints and links -->
    <joint name="camera_depth_joint1" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_link1"/>
      <child link="camera_depth_frame1" />
    </joint>
    <link name="camera_depth_frame1"/>

    <joint name="camera_depth_optical_joint1" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_depth_frame1" />
      <child link="camera_depth_optical_frame1" />
    </joint>
    <link name="camera_depth_optical_frame1"/>
      
    <!-- camera left IR joints and links -->
    <joint name="camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame1" />
      <child link="camera_left_ir_frame" />
    </joint>
    <link name="camera_left_ir_frame"/>

    <joint name="camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_left_ir_frame" />
      <child link="camera_left_ir_optical_frame" />
    </joint>
    <link name="camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame1" />
      <child link="camera_right_ir_frame" />
    </joint>
    <link name="camera_right_ir_frame"/>

    <joint name="camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_right_ir_frame" />
      <child link="camera_right_ir_optical_frame" />
    </joint>
    <link name="camera_right_ir_optical_frame"/>

    <!-- camera color joints and links -->
    <joint name="camera_color_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame1" />
      <child link="camera_color_frame" />
    </joint>
    <link name="camera_color_frame"/>

    <joint name="camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_color_frame" />
      <child link="camera_color_optical_frame" />
    </joint>
    <link name="camera_color_optical_frame"/>


<!-- **********************************************************-->
<!-- GAZEBO DEFINITIONS ***************************************-->

    <!-- Load plugin to the model ("robot" in urdf format)-->
    <gazebo>
        <plugin name="d435" filename="librealsense_gazebo_plugin.so"/>
        <!--<pose frame="">0 0 0.015 0 0 0</pose>-->
    </gazebo>

    <!-- Load parameters to model's main link-->
    <gazebo reference="camera_link1">
        <self_collide>0</self_collide>
        <enable_wind>0</enable_wind>
        <kinematic>0</kinematic>
        <gravity>1</gravity>
        <!--<mu>1</mu>-->
        <mu2>1</mu2>
        <fdir1>0 0 0</fdir1>
        <!--<slip1>0</slip1>
        <slip2>0</slip2>-->
        <kp>1e+13</kp>
        <kd>1</kd>
        <!--<max_vel>0.01</max_vel>
        <min_depth>0</min_depth>-->

        <sensor name="color" type="camera">
            <pose frame="">0 -0.046 0.004 0 0 0</pose>
            <camera name="camera_link1">
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>RGB_INT8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>60</update_rate>
            <visualize>0</visualize>
        </sensor>
        <sensor name="ired1" type="camera">
            <pose frame="">0 -0.06 0.004 0 0 0</pose>
            <camera name="camera_link1">
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>L_INT8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.05</stddev>
            </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>60</update_rate>
            <visualize>0</visualize>
        </sensor>
        <sensor name="ired2" type="camera">
            <pose frame="">0 0.01 0.004 0 0 0</pose>
            <camera name="camera_link1">
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>L_INT8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.05</stddev>
            </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>60</update_rate>
            <visualize>0</visualize>
        </sensor>
        <sensor name="depth" type="depth">
            <pose frame="">0 -0.03 0.004 0 0 0</pose>
            <camera name="camera_link1">
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                    <width>640</width>
                    <height>480</height>
            </image>
            <clip>
                    <near>0.1</near>
                    <far>100</far>
            </clip>
            <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.100</stddev>
            </noise>
            </camera>
            <always_on>1</always_on>
            <update_rate>60</update_rate>
            <visualize>0</visualize>
        </sensor>
    </gazebo>
  </xacro:macro>
</robot>
