<?xml version="1.0"?>
<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 415 camera, in it's
aluminum peripherial evaluation case.
-->

<robot name="sensor_t265" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sensor_t265" params="parent *origin">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="t265_cam_depth_to_left_offset" value="0.023"/>
    <xacro:property name="t265_cam_depth_to_right_offset" value="-0.041"/>
    <xacro:property name="t265_cam_depth_to_imu_offset" value="0.015"/>

    <!-- The following values model the aluminum peripherial case for the
  	t265 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="t265_cam_width" value="0.108"/>
    <xacro:property name="t265_cam_height" value="0.024"/>
    <xacro:property name="t265_cam_depth" value="0.012005"/>
    <xacro:property name="t265_cam_mount_from_center_offset" value="0.0055"/>

    <!-- The following offset is relative the the physical t265 camera peripherial
  	camera tripod mount -->
    <xacro:property name="t265_cam_depth_px" value="${t265_cam_mount_from_center_offset}"/>
    <xacro:property name="t265_cam_depth_py" value="0.010"/>
    <xacro:property name="t265_cam_depth_pz" value="${t265_cam_height/2}"/>

    <material name="aluminum2">
	     <color rgba="0.2 0.2 0.2 1"/>
    </material>


    <!-- camera body, with origin at bottom screw mount -->
    <joint name="camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="camera_bottom_screw_frame" />
    </joint>

    <link name="camera_bottom_screw_frame"/>

    <joint name="camera_link_joint" type="fixed">
      <origin xyz="0 ${t265_cam_depth_py} ${t265_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="camera_bottom_screw_frame"/>
      <child link="camera_link" />
    </joint>

    <link name="camera_link">
      <visual>
      <origin xyz="${t265_cam_depth_px} ${t265_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/t265.stl" scale="0.01 0.01 0.01" />
        </geometry>
        <material name="aluminum2"/>
      </visual>
      <collision>
        <origin xyz="${t265_cam_depth_px} ${t265_cam_depth_py} 0}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/t265.stl" scale="0.01 0.01 0.01" />
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.054" />
        <origin xyz="0 0.0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!-- camera depth joints and links -->
    <joint name="camera_depth_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_link"/>
      <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_depth_frame" />
      <child link="camera_depth_optical_frame" />
    </joint>
    <link name="camera_depth_optical_frame"/>

    <!-- camera left IR joints and links -->
    <joint name="camera_left_joint" type="fixed">
      <origin xyz="0 ${t265_cam_depth_to_left_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_left_frame" />
    </joint>
    <link name="camera_left_frame"/>

    <joint name="camera_left_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_left_frame" />
      <child link="camera_left_optical_frame" />
    </joint>
    <link name="camera_left_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="camera_right_joint" type="fixed">
      <origin xyz="0 ${t265_cam_depth_to_left_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_right_frame" />
    </joint>
    <link name="camera_right_frame"/>

    <joint name="camera_right_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_right_frame" />
      <child link="camera_right_optical_frame" />
    </joint>
    <link name="camera_right_optical_frame"/>

    <!-- IMU joints and links -->
    <joint name="imu_joint" type="fixed">
      <origin xyz="0 ${t265_cam_depth_to_imu_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="imu_frame" />
    </joint>
    <link name="imu_frame"/>
    <gazebo reference="camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

    <!-- **********************************************************-->
<!-- GAZEBO DEFINITIONS ***************************************-->

    <!-- Load parameters to model's main link-->
    <gazebo reference="camera_link">
        <self_collide>0</self_collide>
        <enable_wind>0</enable_wind>
        <kinematic>0</kinematic>
        <gravity>1</gravity>
        <!--<mu>1</mu>-->
        <mu2>1</mu2>
        <fdir1>0 0 0</fdir1>
        <!--<slip1>0</slip1>
        <slip2>0</slip2>-->
        <kp>1e+13</kp>
        <kd>1</kd>
        <!--<max_vel>0.01</max_vel>
        <min_depth>0</min_depth>-->

      <sensor type="multicamera" name="t265">
        <!-- see MultiSenseSLPlugin.h for available modes -->
        <update_rate>30.0</update_rate>
        <pose>0 ${t265_cam_depth_to_left_offset} 0 0 0 0</pose>
        <camera name="left">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>848</width>
            <height>800</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>100</far>
          </clip>
        </camera>
        <camera name="right">
          <pose>0 ${t265_cam_depth_to_right_offset} 0 0 0 0</pose>
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>848</width>
            <height>800</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>100</far>
          </clip>
        </camera>
        <plugin name="t265" filename="libgazebo_ros_multicamera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>30.0</updateRate>
          <cameraName>t265_camera</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameId>camera_link</frameId>
          <frameName>camera_link</frameName>
          <!--<rightFrameName>right_camera_optical_frame</rightFrameName>-->
          <hackBaseline>0.10</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>   
    </gazebo>
    <gazebo>
        <plugin name="imu" filename="libhector_gazebo_ros_imu.so">
            <updateRate>20.0</updateRate>
            <frameId>imu_frame</frameId>
            <bodyName>camera_link</bodyName>
            <topicName>t265/imu</topicName>
            <serviceName>imu</serviceName>
            <xyzOffset>0 0 0</xyzOffset> 
            <rpyOffset>0 0 0</rpyOffset> 
            <gaussianNoise>0</gaussianNoise> 
            <accelDrift>0.5 0.5 0.5</accelDrift>
            <accelGaussianNoise>0.35 0.35 0.3</accelGaussianNoise>
            <rateDrift>0.1 0.1 0.1</rateDrift>
            <rateGaussianNoise>0.05 0.05 0.015</rateGaussianNoise>
            <headingDrift>0.1</headingDrift>
            <headingGaussianNoise>0.05</headingGaussianNoise>
        </plugin>
    </gazebo>

  </xacro:macro>
</robot>
