<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->

<robot name="mount_t265_mount_t265_d435" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="rsMount" params="parent *origin">
    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values model the aluminum peripherial case for the
  	mount_t265_d435 camera, with the camera joint represented by the actual 
  	peripherial camera tripod mount -->
    <xacro:property name="mount_t265_d435_cam_height" value="0.045"/>
    <xacro:property name="mount_t265_d435_cam_depth" value="0.02505"/>
    <xacro:property name="mount_t265_d435_cam_mount_from_center_offset" value="0.0049"/>
  
    <!-- The following offset is relative the the physical mount_t265_d435 camera peripherial
  	camera tripod mount -->
    <xacro:property name="mount_t265_d435_cam_depth_px" value="${mount_t265_d435_cam_mount_from_center_offset}"/>
    <xacro:property name="mount_t265_d435_cam_depth_py" value="-0.0075"/>
    <xacro:property name="mount_t265_d435_cam_depth_pz" value="${mount_t265_d435_cam_height/2}"/>

    <material name="aluminum">
	  <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- camera body, with origin at bottom screw mount -->
    <joint name="mount_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="mount_bottom_screw_frame" />
    </joint>
    <link name="mount_bottom_screw_frame"/>

    <joint name="mount_link_joint" type="fixed">
      <origin xyz="0 ${mount_t265_d435_cam_depth_py} ${mount_t265_d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="mount_bottom_screw_frame"/>
      <child link="mount_link" />
    </joint>

    <link name="mount_link">
      <visual>
      <origin xyz="${mount_t265_d435_cam_mount_from_center_offset} ${-mount_t265_d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/mount_t265_d435.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <origin xyz="${mount_t265_d435_cam_mount_from_center_offset} ${-mount_t265_d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://realsense2_description/meshes/mount_t265_d435.stl" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.264" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <gazebo reference="mount_link">
    <material>Gazebo/Blue</material>
  </gazebo>


  </xacro:macro>
</robot>
